Database:
  Host: "127.0.0.1"
  Port: "3305"
  DBName: "project-go"
  DBUser: "root"
  DBPass: "1234"

Server:
  Address: ":5000"

Redis:
  Host: "localhost:6378"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password:
  DB: 0